server:
  port: 8080 # 指定端口号

spring:
  datasource:
    url: jdbc:mysql://localhost:3307/CareerCoach?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    redis:
      host: localhost
      port: 6379

# Cal.com 集成配置
cal:
  api-url: https://api.cal.com/v2
  base-url: https://cal.com
  username: kris-l-unimxu
  event-type-id: 4024625
  event-type-slug: 30min
  time-zone: Australia/Sydney
  # teamslug: #Team模式下的slot显示有bug没法用

# JWT配置
jwt:
  secret: "PXrQbuCwXwOZzkML/Vm2S5rSwt1iybvmKtGDzVEu+Hc="
  expiration: 3600000 # 1小时

# 加密配置
encryption:
  secret-key: "CareerCoach2024Secret1234567890"  
